FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src

COPY src/ ./src/

RUN dotnet restore src/ImageDrop.ImageProcessing.Worker/ImageDrop.ImageProcessing.Worker.csproj

RUN dotnet publish src/ImageDrop.ImageProcessing.Worker/ImageDrop.ImageProcessing.Worker.csproj \
    -c Release \
    -o /app/publish \
    --no-restore


FROM mcr.microsoft.com/dotnet/runtime:10.0 AS final

WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "ImageDrop.ImageProcessing.Worker.dll"]