FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src

COPY src/ ./src/

RUN dotnet restore src/ImageDrop.Api/ImageDrop.Api.csproj

RUN dotnet publish src/ImageDrop.Api/ImageDrop.Api.csproj \
    -c Release \
    -o /app/publish \
    --no-restore


FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final

WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "ImageDrop.Api.dll"]