namespace ImageDrop.Shared.Constants.Enums;

public enum ErrorStatusCode
{
    USER_ALREADY_EXISTS,
    USER_NOT_FOUND,
    USER_INVALID_CREDENTIALS,
    USER_PASSWORD_IS_NOT_VALID,
    USER_INVALID_REFRESH_TOKEN,
    
    IMAGE_NOT_FOUND,
    INVALID_FILE,
    INVALID_FILE_TYPE,
    
    UNAUTHORIZED,
    FORBIDDEN,
    VALIDATION_ERROR,
    TOO_MANY_REQUESTS,
    INTERNAL_SERVER_ERROR
}